export const ADD_ITEM = 'INCOME_ADD_ITEM';
export const ADD_DONE = 'INCOME_ADD_DONE';
export const ADD_ERROR = 'INCOME_ADD_ERROR';
export const START_FETCHING = 'INCOME_START_FETCHING';
export const FETCHING_DONE = 'INCOME_FETCHING_DONE';
export const FETCHING_ERROR = 'INCOME_FETCHING_ERROR';
