export const ADD_ITEM = 'OUTCOME_ADD_ITEM';
export const ADD_DONE = 'OUTCOME_ADD_DONE';
export const ADD_ERROR = 'OUTCOME_ADD_ERROR';
export const START_FETCHING = 'OUTCOME_START_FETCHING';
export const FETCHING_DONE = 'OUTCOME_FETCHING_DONE';
export const FETCHING_ERROR = 'OUTCOME_FETCHING_ERROR';
